INSERT INTO t_quiz (id, title, description) VALUES ('0', 'craw', 'craw');
INSERT INTO t_questions (quiz_id, title, options_id) VALUES ('0', 'gdvs', 0);
INSERT INTO t_options (id, name, result) VALUES ('0', 'dg', 1);
INSERT INTO t_options (id, name, result) VALUES ('0', ' df', 0);
INSERT INTO t_questions (quiz_id, title, options_id) VALUES ('0', 'gdvs', 0);
INSERT INTO t_options (id, name, result) VALUES ('0', ' s', 0);
INSERT INTO t_options (id, name, result) VALUES ('0', ' grwa', 1);
INSERT INTO t_quiz (id, title, description) VALUES ('1', 'craw', 'craw');
INSERT INTO t_questions (quiz_id, title, options_id) VALUES ('1', 'gdvs', 2);
INSERT INTO t_options (id, name, result) VALUES ('2', 'dg', 1);
INSERT INTO t_options (id, name, result) VALUES ('2', ' df', 0);
INSERT INTO t_questions (quiz_id, title, options_id) VALUES ('1', 'gdvs', 2);
INSERT INTO t_options (id, name, result) VALUES ('2', ' s', 0);
INSERT INTO t_options (id, name, result) VALUES ('2', ' grwa', 1);
INSERT INTO t_quiz (id, title, description) VALUES ('2', 'craw', 'craw');
INSERT INTO t_questions (quiz_id, title, options_id) VALUES ('2', 'gdvs', 4);
INSERT INTO t_options (id, name, result) VALUES ('4', 'dg', 1);
INSERT INTO t_options (id, name, result) VALUES ('4', ' df', 0);
INSERT INTO t_questions (quiz_id, title, options_id) VALUES ('2', 'gdvs', 4);
INSERT INTO t_options (id, name, result) VALUES ('4', ' s', 0);
INSERT INTO t_options (id, name, result) VALUES ('4', ' grwa', 1);
